lessonmanagement/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('profile/<int:teacher_id>/', views.profile_detail, name="profile_detail"),
    path('lessons/', views.lessons, name='lessons'),
    path('lessons/<int:schoolyear>/', views.lessons, name="lessons_schoolyear"),
    
    path('lessons/week/', views.week_lessons, name='now_week_lessons'),
    path('lessons/week/<int:url_week>/', views.week_lessons, name='week_lessons'),

    path('lessons/empty/', views.emptylesson, name="emptylesson"),
    path('lesson/open/<int:id>/', views.open_lesson, name="open_lesson"),
    path('lesson/<int:id>/', views.lesson, name="lesson"),
    path('lesson/edit/<int:lesson_id>/', views.edit_lesson, name="edit_lesson"),
    path('lesson/add/', views.addlesson, name="addlesson"),
    path('lesson/add/<int:url_week>/', views.addlesson, name="addlesson_week"),
    path('lessons/add/<str:subject>/', views.add_lesson_subject, name="add_lesson_subject"),
    path('lessons/add/<str:subject>/<int:url_week>/', views.add_lesson_subject, name="add_lesson_subject_week"),
    path('lessons/add/error/', views.no_permisson_add_lesson, name = 'no_permisson_add_lesson'),
    path('lessons/<str:subject>/', views.lessons_subject, name="lessons_subject"),

    # lịch báo giảng
    path('schedule/add/', views.add_schedule, name = 'add_schedule'),
    path('schedule/add/<int:lesson_id>/', views.add_lesson_schedule, name = 'add_lesson_schedule'),
    path('schedule/<str:username_url>/', views.schedule, name = 'now_schedule'),
    path('schedule/<str:username_url>/<int:url_week>/', views.schedule, name = 'schedule'),

    # DUYệt GIÁO ÁN
     path('checklessons/<int:year>/<str:subject>/', views.check_lessons_subject, name='check_lessons_subject'),
     path('checklesson/<int:lesson_id>/', views.check_lesson, name='check_lesson'),
     path('checklesson/open/<int:lesson_id>/', views.check_open_lesson, name='check_open_lesson'),
    # THỐNG KÊ LỊCH BÁO GIẢNG
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/<int:week>/', views.dashboard, name='dashboard_week'),
    path('emptyschedule/', views.emptyschedule, name = 'emptyschedule'),

    path('teacher/<int:teacher_id>/', views.teacher, name='teacher'),

    #Tải lên file
    path('upload/', views.upload_file, name='upload'),

    path('bb/', views.bb, name='bb'),

    #xóa giáo án update ngày 02/11/2021
    path('removelesson/<int:id>/', views.removelesson, name='removelesson'),

] 

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('', include('lessonmanagement.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

lessonmanagement/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from django.db.models import F
from django.utils.text import slugify
from django.utils import timezone

# thời gian có thể sửa giáo án sau khi upload tính bằng phút
TIME_OUT_EDIT = 1440

LEVEL_CHOICES = [
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9)
    ]

# Lấy khối học từ năm bắt đầu vào trường
def class_level_def(year):
    now = datetime.datetime.now()
    i = 0
    if (now.month < 9):
        i =  (now.year - year) + 5
    else:
        i = (now.year - year) + 6
    if i in [6,7,8,9]:
        return i
    else:
        return year

# năm học đang đào tạo
def schoolyear_learning():
    now = datetime.datetime.now()
    listyear = []
    for i in [0,1,2,3,4]:
        if now.month < 9:
            listyear.append(now.year - i)
        else:
            listyear.append(now.year + 1 -i )
    return listyear


#lấy niên khoá từ class level
def school_year_def(upload_time):
    if (upload_time.month < 9):
        return upload_time.year -1
    else:
        return upload_time.year

#lấy năm vào trường của lớp từ level
def level_to_startyear(level):
    now = datetime.datetime.now()
    if now.month < 9:
        return (now.year + 5 - level)
    else:
        return (now.year + 6 - level)


# có đang đào tạo tại trường
def is_learning_def(class_level):
    return class_level in [6,7,8,9]

def q_schoolyear():
    return Schoolyear.objects.get(is_active=True)
# đổi từ class level sang năm vào trường của một lớp
def level_to_startyear(level):
    now = datetime.datetime.now()
    if now.month < 8:
        return (now.year + 5 - level)
    else:
        return (now.year + 6 - level)

def class_level_def(year):
    now = datetime.datetime.now()
    i = 0
    if (now.month < 8):
        i = (now.year - year) + 5
    else:
        i = (now.year - year) + 6
    if i in [6, 7, 8, 9]:
        return i
    else:
        return year

# năm bắt đầu của niên khóa hiện tại
def current_schoolyear():
    now = datetime.datetime.now()
    year = now.year
    month = now.month
    if month > 8:
        return year
    else:
        return year - 1

# đổi ngày hiện tại sang tuần tương ứng của năm học
def now_week_schoolyear(schoolyear):
    start_day = schoolyear.start_date
    start_monday = start_day + datetime.timedelta(days=-start_day.weekday())
    today = datetime.date.today()
    week = (today - start_monday)/7
    number_week = week.days
    if number_week < 0 or number_week > 52:
        number_week = 0
    return number_week
    

# đổi ngày bất kì sang tuần tương ứng của năm học
def day_week_schoolyear(schoolyear, d):
    start_day = schoolyear.start_date
    start_monday = start_day + datetime.timedelta(days=-start_day.weekday())
    week = (d - start_monday)/7
    return week.days

# lấy ngày thứ hai của tuần năm học
def monday_week_schoolyear(schoolyear, week):
    start_day = schoolyear.start_date
    start_monday = start_day + datetime.timedelta(days=-start_day.weekday())
    now_monday = start_monday + datetime.timedelta(days = week*7)
    return now_monday




# ABSTRACT MODEL ---------------------------------------------------------------

# Abstract for: School, Subject, GroupSubject
class SchoolAbstract(models.Model):
    title = models.CharField(max_length=50, verbose_name="Tiêu đề")
    description = models.CharField(max_length=200, verbose_name="Mô tả sơ lược", blank=True)
    cover = models.ImageField(upload_to="coverimages/", verbose_name="Ảnh bìa", null = True, blank = True)
    class Meta:
        abstract = True
    def __str__(self):
        return self.title

# Abstract for: SubjectTeacher, ClassyearManager, GroupSubjectManager, SchoolManager
class MembershipAbstract(models.Model):
    teacher = models.ForeignKey(
        "Teacher",
        on_delete=models.CASCADE,
        verbose_name='Giáo viên',
        limit_choices_to={'is_work': True}
        )
    startdate = models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')
    enddate = models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')
    is_active = models.BooleanField(default=True, blank=True, verbose_name="Có hiệu lực không")
    schoolyear = models.ForeignKey(
        'Schoolyear',
        on_delete=models.CASCADE,
        default=q_schoolyear
    )

    class Meta:
        abstract = True

# MODEL ---------------------------------------------------------------------------
# GIÁO VIÊN
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Tài khoản đăng nhập")
    firstname = models.CharField("Họ",max_length=20, blank=True)
    lastname = models.CharField("Tên", max_length=20, blank=True)
    zalo_number = models.DecimalField(verbose_name="Số điện thoại",help_text="Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo từ ban giám hiệu", max_digits=12, decimal_places=0,null=True, blank=True)
    birth_date = models.DateField("Ngày sinh", null=True, blank=True)
    SEX_CHOICES = [
    ('male', 'Nam'),
    ('female', 'Nữ')
    ]
    sex = models.CharField(verbose_name="Giới tính", max_length=6, choices=SEX_CHOICES, null=True, blank=True)
    #chuyên môn chính
    main_subject = models.ForeignKey("Subject",on_delete=models.SET_NULL,null=True,blank=True, verbose_name="Chuyên môn chính")
    EDUCATION_LEVEL_CHOICES = [
        ('inter', 'Trung Cấp'),
        ('college', 'Cao Đẳng'),
        ('university', 'Đại Học'),
        ('master', 'Thạc Sĩ')
    ]
    education_level = models.CharField(max_length=20, choices=EDUCATION_LEVEL_CHOICES, null=True, blank=True)
    is_work = models.BooleanField("Có đang công tác", default=True)
    def user_directory_path(instance, filename):
        return 'user_{0}/{1}'.format(instance.user.id, filename)
    avatar = models.ImageField("Ảnh đại diện", upload_to=user_directory_path, blank=True, null=True)
    #tên đầy đủ
    def full_name(self):
        return ('%s %s') % (self.firstname, self.lastname)
    #tất cả giáo án
    def lesson_list(self):
        return self.lesson_set.filter(teacher = self.user.id)
    #môn dạy và lớp dạy phục vụ cho sidebar.html
    def current_schoolyear(self):
        return q_schoolyear()

    def subjectclassyear(self):
        return SubjectClassyear.objects.filter(
            teacher=self, is_active=True, schoolyear=q_schoolyear()
        )

    def subject_classyeartitle_list(self):
        return self.subjectclassyear_set.filter(
            schoolyear=self.current_schoolyear()).order_by('subject__subject__title').values('subject__subject__title', 'classyear__startyear__start_date__year','subject__subject__group__title', 'classyear__title','subject__total_lesson', 'subject__week_lesson').distinct()
    #giáo án mới nhất phục vụ trang dashboard
    def latest_lesson(self):
        return Lesson.objects.filter(teacher=self.user.teacher.id).order_by('-upload_time')[:3]
    #chức danh phục vụ cho trang dashboard
    def managers(self):
        managers = {}
        teacher = self.user.teacher.id
        school_manager = SchoolManager.objects.filter(teacher=teacher).filter(is_active=True)
        if school_manager:
            school_manager = school_manager.latest('-id')
            managers['school'] = school_manager
        classyear_manager = ClassyearManager.objects.filter(teacher=teacher).filter(is_active=True)
        if classyear_manager:
            classyear_manager = classyear_manager.latest('-id')
            managers['class'] = classyear_manager
        return managers
    #thống kê số lượng giáo án
    def count_lesson(self):
        now = datetime.datetime.now()
        count = {}
        teacher = self.user.teacher.id
        lessons = Lesson.objects.filter(teacher=teacher)
        count['total'] = lessons.count()
        current_year = [school_year_def(now), school_year_def(now)+1]
        lesson_current_year = lessons.filter(upload_time__year__in = current_year )
        count['year'] = lesson_current_year.count()
        lesson_current_month = lessons.filter(upload_time__year__in = current_year).filter(upload_time__month = now.month)
        count['month'] = lesson_current_month.count()
        return count

    def target_lesson_week(self):
        subjectclassyear = SubjectClassyear.objects.filter(
            schoolyear=self.current_schoolyear(), teacher=self.id
        )
        count = 0
        for i in subjectclassyear:
            count += i.subject.week_lesson

        return count

    def week_lesson(self):
        schoolyear = q_schoolyear()
        week= now_week_schoolyear(schoolyear)
        teacher=self.id
        lesson_week = Lesson.objects.filter(
            teacher=teacher, week=week
        )
        return(lesson_week.count())

    def is_complete_subjectclassyear(self):
        return self.week_lesson() >= self.target_lesson_week()

    class Meta:
        verbose_name = "Giáo viên"
        verbose_name_plural = "Giáo viên"

    def __str__(self):
        return self.full_name()

# TRƯỜNG HỌC
class School(SchoolAbstract):
    class Meta:
        verbose_name = "Trường Học"
        verbose_name_plural = "Trường Học"

# QUẢN LÝ TRƯỜNG HỌC
class SchoolManager(MembershipAbstract):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    ROLE_CHOICES = [
    ('submanager', 'Hiệu phó'),
    ('manager', 'Hiệu trưởng'),
    ('member', 'Khác')
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, verbose_name='Vị trí')
    class Meta:
        verbose_name = "Quản lý trường học "
        verbose_name_plural = "Quản lý trường học"
    def __str__(self):
        return '%s - %s ' % (self.teacher.full_name(), self.role)
        
# NĂM HỌC        
class Schoolyear(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, verbose_name="Trường")
    total_week = models.IntegerField("Tổng số tuần học")

lessonmanagement/forms.py
from django.forms import ModelForm
from django import forms
from .models import LectureFile

class LectureFileForm(ModelForm):
    class Meta:
        model = LectureFile
        fields = ['title', 'file', 'user']
        widgets = {'user': forms.HiddenInput()}

class CheckForm(forms.Form):
    pwd = forms.PasswordInput()

lessonmanagement/templates/profile/create_profile.html
{{ form.as_table }}

lessonmanagement/templates/profile/profile.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
{% load lessonmanagement_extras %}
{% with teacher=request.user.teacher %}
<div class="row justify-content-center mt-4">
  <div class="col-lg-5">
    {% include 'notification/success.html' %}
  </div>
</div>
<div class="row mt-lg-5 mt-4">
  <div class="col-lg-4">
    <div class="d-flex flex-column  align-items-center">
      {% if teacher.avatar %}
      <img src="{{ teacher.avatar.url }}" alt="Ảnh đại diện của {{ request.user.username }}" class=" rounded-circle "
        height="250px">
      {% else %}
      <h4 class="text-danger">Chưa có ảnh đại diện</h4>
      {% endif %}
      <a class="btn btn-sm btn-outline-dark mt-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#update_avatar" aria-expanded="false" aria-controls="collapseExample">
        <i class="far fa-edit me-1"></i>Thay đổi ảnh đại diện
      </a>
      <div class="collapse mt-4" id="update_avatar">
        <div class="card card-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="avatar" class="form-label">Tải lên ảnh mới</label>
            <input class="form-control" type="file" id="avatar" name="avatar">
            <a class="btn btn-outline-primary mt-4" type="button" data-bs-toggle="collapse"
              data-bs-target="#update_avatar" aria-expanded="false" aria-controls="collapseExample">Hủy
            </a>
            <button type="submit" class="btn btn-primary ms-2 mt-4" name="btnavatar">Cập nhập ảnh đại diện</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col">
    <h4 class="mt-3 mt-lg-0">Xin chào!</h4>
    <h1> {{ teacher.full_name }}</h1>
    <span class="text-muted">
      Tài khoản đăng nhập: {{ request.user.username }}
    </span>
    <a class="btn btn-sm btn-outline-danger mt-lg-0 mt-3 ms-lg-3" href="#" data-bs-toggle="collapse"
      data-bs-target="#collapsePwd" aria-expanded="false" aria-controls="collapseExample"><i
        class="fas fa-key me-2"></i>Thay đổi mật khẩu
    </a>
    <div class="collapse mt-3 mb-3" id="collapsePwd">
      <div class="card card-body">
        <form action="" method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="changepassword" class="form-label">Mật khẩu mới</label>
            <input type="password" class="form-control" id="changepassword" name="new_password">
          </div>
          <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" id="showpwd" onclick="showPwd()">
            <label class="form-check-label" for="showpwd">Hiển thị mật khẩu</label>
          </div>
          <a href="#" class="btn btn-outline-danger me-2 mt-4" data-bs-toggle="collapse"
            data-bs-target="#collapsePwd">Hủy</a>
          <button type="submit" class="btn btn-danger mt-4" name="btnchangepassword">Thay đổi mật khẩu</button>
        </form>
        <script>
          function showPwd() {
            var x = document.getElementById("changepassword");
            if (x.type === "password") {
              x.type = "text";
            } else {
              x.type = "password";
            }
          }
        </script>
      </div>
    </div>
    <h5>Thông tin cá nhân</h5>
    <ul class="list-unstyled">
      <li><i class="far fa-user fa-fw me-2 text-muted"></i> {{ teacher.full_name }}
      <li>
      <li><i class="fas fa-venus-mars fa-fw me-2 text-muted"></i> {{ teacher.get_sex_display }}
      <li>
      <li><i class="fas fa-birthday-cake fa-fw me-2 text-muted"></i> {{ teacher.birth_date|date:"SHORT_DATE_FORMAT" }}
      <li>
      <li><i class="fas fa-mobile-alt fa-fw me-2 text-muted"></i> <a href="tel:{{ teacher.zalo_number }}"
          class="text-decoration-none"> {{ teacher.zalo_number }}</a>
      <li>
    </ul>
    <button class="btn btn-sm btn-success mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#changeprofile"
      aria-expanded="false" aria-controls="collapseExample">
      <i class="far fa-edit me-1"></i>Thay đổi thông tin cá nhân
    </button>
    <div class="collapse mt-3" id="changeprofile">
      <div class="card card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-4">
              <div class="mb-3">
                <label for="fname" class="form-label">Họ</label>
                <input type="text" class="form-control" id="fname" name="fname" value="{{ teacher.firstname }}">
              </div>
            </div>
            <div class="col-lg-2">
              <div class="mb-3">
                <label for="lname" class="form-label">Tên</label>
                <input type="text" class="form-control" id="lname" name="lname" value="{{ teacher.lastname }}">
              </div>
            </div>
            <div class="col-lg-2">
              <label for="sex" class="form-label">Giới tính</label>
              <select class="form-select" aria-label="Default select example" id="sex" name="sex">
                <option selected>{{ teacher.get_sex_display }}</option>
                <option value="male">Nam</option>
                <option value="female">Nữ</option>
              </select>
            </div>
            <div class="col-lg-3">
              <div class="mb-3">
                <label for="birthdate" class="form-label">Ngày sinh</label>
                <input type="date" class="form-control" name="birthdate" value="{{ teacher.birth_date|date:'Y-m-d' }}">
              </div>
            </div>
            <div class="col-lg-4">
              <div class="mb-3">
                <label for="mobile" class="form-label">Số điện thoại</label>
                <input type="text" class="form-control" value="{{ teacher.zalo_number }}" name="number">
              </div>
            </div>
          </div>
          <a class="btn btn-outline-success mt-4 me-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#changeprofile" aria-expanded="false" aria-controls="collapseExample">
            Hủy
          </a>
          <button class="btn btn-success mt-4" type="submit" name='changeprofile'>
            Cập nhật thông tin cá nhân
          </button>
        </form>
      </div>
    </div>
    <hr>
    <h5>Thông tin công việc</h5>
    <ul class="list-unstyled">
      <li><i class="fas fa-graduation-cap fa-fw me-2 text-muted"></i> {{ teacher.get_education_level_display }} {{teacher.main_subject}}
        <button class="btn btn-sm btn-primary ms-4" type="button" data-bs-toggle="collapse"
          data-bs-target="#change_education" aria-expanded="false" aria-controls="subject">
          Thay đổi
        </button>
        <div class="collapse my-3" id="change_education">
          <div class="card card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-3">
                  <label for="education" class="form-label">Trình độ</label>
                  <select name="education" id="education" class="form-select">
                    <option selected>{{ teacher.get_education_level_display}}</option>
                    <option value="inter">Trung Cấp</option>
                    <option value="college">Cao Đẳng</option>
                    <option value="university">Đại Học</option>
                    <option value="master">Thạc Sĩ</option>
                  </select>
                </div>
                <div class="col-lg-4">
                  <label for="subject" class="form-label">Chuyên môn</label>
                  <select name="subject" id="subject" class="form-select">
                    <option selected>{{ teacher.main_subject.title }}</option>
                    {% for i in list_subject %}
                    <option value="{{ i.id }}">{{ i.title }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <a class="btn btn-outline-success mt-4 me-2" type="button" data-bs-toggle="collapse"
                data-bs-target="#change_education" aria-expanded="false" aria-controls="collapseExample">
                Hủy
              </a>
              <button class="btn btn-success mt-4" type="submit" name='btnchangeeducation'>
                Thay đổi
              </button>
            </form>
          </div>
        </div>
      </li>
      {% if teacher.managers.school %}
      <li>
        <i class="fas fa-school fa-fw me-2 text-muted"></i> {{ teacher.managers.school.get_role_display }} <a href="#"
          class="text-decoration-none"> {{ teacher.managers.school.school.title }}</a>.
      </li>
      {% endif %}
        {%if teacher.managers.group%}{{ teacher.managers.group.get_role_display }} <a href="#" class="text-decoration-none">Bộ
        môn {{ teacher.managers.group.group.title }}</a>.{% endif %}</li>
      {% if teacher.managers.class %}
      <li><i class="fas fa-users fa-fw me-2 text-muted"></i> Chủ nhiệm lớp <a href="#" class="text-decoration-none"> {{
          teacher.managers.class }}</a>.</li>
      {% endif %}

    </ul>
  </div>
</div>
{% endwith %}
{% endblock %}

lessonmanagement/templates/profile/profile_detail.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
{% load lessonmanagement_extras %}
{% with teacher=teacher_context %}
<div class="row justify-content-center mt-4">
  <div class="col-lg-5">
    {% include 'notification/success.html' %}
  </div>
</div>
<div class="row mt-lg-5 mt-4">
  <div class="col-lg-4">
    <div class="d-flex flex-column  align-items-center">
      {% if teacher.avatar %}
      <img src="{{ teacher.avatar.url }}" alt="Ảnh đại diện của {{ request.user.username }}" class=" rounded-circle "
        height="250px">
      {% else %}
      <h4 class="text-danger">Chưa có ảnh đại diện</h4>
      {% endif %}
    </div>
  </div>
  <div class="col">
    <h4 class="mt-3 mt-lg-0">Thông tin giáo viên</h4>
    <h1> {{ teacher.full_name }} <small class="text-muted">@{{teacher.user}}</small></h1>
    <hr>
    <h5>Thông tin cá nhân</h5>
    <ul class="list-unstyled">
      <li><i class="far fa-user fa-fw me-2 text-muted"></i> {{ teacher.full_name }}
      <li>
      <li><i class="fas fa-venus-mars fa-fw me-2 text-muted"></i> {{ teacher.get_sex_display }}
      <li>
      <li><i class="fas fa-birthday-cake fa-fw me-2 text-muted"></i> {{ teacher.birth_date|date:"SHORT_DATE_FORMAT" }}
      <li>
      <li><i class="fas fa-mobile-alt fa-fw me-2 text-muted"></i> <a href="tel:{{ teacher.zalo_number }}"
          class="text-decoration-none"> {{ teacher.zalo_number }}</a>
      <li>
    </ul>
    <hr>
    <h5>Thông tin công việc</h5>
    <ul class="list-unstyled">
      <li><i class="fas fa-graduation-cap fa-fw me-2 text-muted"></i> {{ teacher.get_education_level_display }} {{teacher.main_subject}}
      </li>
      
      {% if subjects %}
      <li><i class="fas fa-pen-alt me-2 fa-fw text-muted"></i> Duyệt giáo án môn:
        {% for subject in subjects %}
        {{ subject.subject.title }}
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </li>
    {% endif %}
    </ul>
  </div>
</div>
{% endwith %}
{% endblock %}